### ISSUE TITLE
在Ubuntu16.04上安装失败

### ISSUE THREAD

**Issue by Moying-moe** [iTXTech/mcl-installer#10]
```
root@iZwz9dnj5dq:~/mirai# ./mcl-installer-1.0.2-linux-amd64

iTXTech MCL Installer 1.0.2 [OS: linux]
Licensed under GNU AGPLv3.
https://github.com/iTXTech/mcl-installer

iTXTech MCL and Java will be downloaded to "/root/mirai"

Checking existing Java installation.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:139:54
stack backtrace:
   0:     0x7f3e958136a1 - <unknown>
   1:     0x7f3e95772cac - <unknown>
   2:     0x7f3e95812df1 - <unknown>
   3:     0x7f3e95812840 - <unknown>
   4:     0x7f3e9581216d - <unknown>
   5:     0x7f3e9582f3f3 - <unknown>
   6:     0x7f3e9582f36c - <unknown>
   7:     0x7f3e9582f31d - <unknown>
   8:     0x7f3e957715a0 - <unknown>
   9:     0x7f3e95773ee2 - <unknown>
  10:     0x7f3e9575b205 - <unknown>
  11:     0x7f3e957667f5 - <unknown>
  12:     0x7f3e957613ad - <unknown>
  13:     0x7f3e95763c7a - <unknown>
  14:     0x7f3e95757d7a - <unknown>
  15:     0x7f3e9576df35 - <unknown>
  16:     0x7f3e93db0840 - __libc_start_main
  17:     0x7f3e95756e4a - <unknown>
  18:                0x0 - <unknown>
Aborted

```

os: Ubuntu16.04(AliYun)

**Comment by Moying-moe** [comment]
换用新版后第一次安装失败，信息如下：
```
root@iZwz9dnj5dq:~/mirai# ./mcl-installer-2827601-linux-amd64
iTXTech MCL Installer 1.0.2 [OS: linux]
Licensed under GNU AGPLv3.
https://github.com/iTXTech/mcl-installer

iTXTech MCL and Java will be downloaded to "/root/mirai"

Checking existing Java installation.
Error occurred while checking Java installation

Would you like to install Java? (Y/N, default: Y) y
Java version (8-15, default: 11):
JRE or JDK (1: JRE, 2: JDK, default: JRE):
Binary Architecture (default: x64):
Fetching file list for jre version 11 on x64
Testing Java Executable: java
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:242:53
stack backtrace:
   0:     0x7f533ba21b31 - <unknown>
   1:     0x7f533b9496bc - <unknown>
   2:     0x7f533ba21281 - <unknown>
   3:     0x7f533ba20cd0 - <unknown>
   4:     0x7f533ba205fd - <unknown>
   5:     0x7f533ba3d883 - <unknown>
   6:     0x7f533ba3d7fc - <unknown>
   7:     0x7f533ba3d7ad - <unknown>
   8:     0x7f533b947fb0 - <unknown>
   9:     0x7f533b94a8f2 - <unknown>
  10:     0x7f533b93358e - <unknown>
  11:     0x7f533b940d27 - <unknown>
  12:     0x7f533b93918a - <unknown>
  13:     0x7f533b93c083 - <unknown>
  14:     0x7f533b93011a - <unknown>
  15:     0x7f533b9448d9 - <unknown>
  16:     0x7f533a6a0840 - __libc_start_main
  17:     0x7f533b92f1ea - <unknown>
  18:                0x0 - <unknown>
Aborted

```
第二次运行目前未报错，正在下载mcl-1.0.5.zip

**Comment by Moying-moe** [comment]
已经成功安装，但是第一次安装失败的原因暂时不知晓，可能和下载有关，可以排查一下

**Comment by DengYuncheng27** [comment]
相同的问题，lastest版本安装不行，换成最新的版本后成功安装~
