### ISSUE TITLE
下载依赖失败

### ISSUE THREAD

**Issue by xiguasamall** [iTXTech/mcl-installer#30]
12:53:18 [INFO] Verifying "net.mamoe:mirai-console" v2.10.0-RC2
 12:53:18 [ERROR] "net.mamoe:mirai-console" is corrupted.
 12:53:19 [ERROR] Cannot download package "net.mamoe:mirai-console"
 12:53:19 [ERROR] The local file "net.mamoe:mirai-console" is still corrupted, please check the network.
 12:53:19 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.10.0-RC2
 12:53:19 [ERROR] "net.mamoe:mirai-console-terminal" is corrupted.
 12:53:19 [ERROR] Cannot download package "net.mamoe:mirai-console-terminal"
 12:53:19 [ERROR] The local file "net.mamoe:mirai-console-terminal" is still corrupted, please check the network.
 12:53:19 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.0-RC2
 12:53:19 [ERROR] "net.mamoe:mirai-core-all" is corrupted.
 12:53:19 [ERROR] Cannot download package "net.mamoe:mirai-core-all"
 12:53:19 [ERROR] The local file "net.mamoe:mirai-core-all" is still corrupted, please check the network.
 12:53:19 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
 12:53:19 [ERROR] "org.itxtech:mcl-addon" is corrupted.
 12:53:20 [ERROR] Cannot download package "org.itxtech:mcl-addon"
 12:53:20 [ERROR] The local file "org.itxtech:mcl-addon" is still corrupted, please check the network.
 12:53:20 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.nio.file.NoSuchFileException: libs\mirai-console-2.10.0-RC2.jar (boot.js#98)

**Comment by CHN-Rudius** [comment]
我也失败了，有解决方法吗

**Comment by gimfia** [comment]
我也失败了

 14:46:20 [INFO] Verifying "net.mamoe:mirai-console" v2.10.0
 14:46:20 [ERROR] "net.mamoe:mirai-console" is corrupted.
 14:46:22 [ERROR] Cannot download package "net.mamoe:mirai-console"
 14:46:22 [ERROR] The local file "net.mamoe:mirai-console" is still corrupted, please check the network.
 14:46:22 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.10.0
 14:46:22 [ERROR] "net.mamoe:mirai-console-terminal" is corrupted.
 14:46:23 [ERROR] Cannot download package "net.mamoe:mirai-console-terminal"
 14:46:23 [ERROR] The local file "net.mamoe:mirai-console-terminal" is still corrupted, please check the network.
 14:46:23 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.0
 14:46:23 [ERROR] "net.mamoe:mirai-core-all" is corrupted.
 14:46:24 [ERROR] Cannot download package "net.mamoe:mirai-core-all"
 14:46:24 [ERROR] The local file "net.mamoe:mirai-core-all" is still corrupted, please check the network.
 14:46:24 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
 14:46:24 [ERROR] "org.itxtech:mcl-addon" is corrupted.
 14:46:25 [ERROR] Cannot download package "org.itxtech:mcl-addon"
 14:46:25 [ERROR] The local file "org.itxtech:mcl-addon" is still corrupted, please check the network.
 14:46:25 [INFO] Verifying "net.mamoe:mirai-api-http" v1.10.0
 14:46:25 [ERROR] "net.mamoe:mirai-api-http" is corrupted.
 14:46:26 [ERROR] Cannot download package "net.mamoe:mirai-api-http"
 14:46:26 [ERROR] The local file "net.mamoe:mirai-api-http" is still corrupted, please check the network.
 14:46:26 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.nio.file.NoSuchFileException: libs\mirai-console-2.10.0.jar (boot.js#98)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at script(boot.js:98)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.nio.file.NoSuchFileException: libs\mirai-console-2.10.0.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
        at java.base/java.nio.file.Files.readAttributes(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        ... 20 more

**Comment by CHN-Rudius** [comment]
> 我也失败了
> 
> 14:46:20 [INFO] Verifying "net.mamoe:mirai-console" v2.10.0 14:46:20 [ERROR] "net.mamoe:mirai-console" is corrupted. 14:46:22 [ERROR] Cannot download package "net.mamoe:mirai-console" 14:46:22 [ERROR] The local file "net.mamoe:mirai-console" is still corrupted, please check the network. 14:46:22 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.10.0 14:46:22 [ERROR] "net.mamoe:mirai-console-terminal" is corrupted. 14:46:23 [ERROR] Cannot download package "net.mamoe:mirai-console-terminal" 14:46:23 [ERROR] The local file "net.mamoe:mirai-console-terminal" is still corrupted, please check the network. 14:46:23 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.0 14:46:23 [ERROR] "net.mamoe:mirai-core-all" is corrupted. 14:46:24 [ERROR] Cannot download package "net.mamoe:mirai-core-all" 14:46:24 [ERROR] The local file "net.mamoe:mirai-core-all" is still corrupted, please check the network. 14:46:24 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2 14:46:24 [ERROR] "org.itxtech:mcl-addon" is corrupted. 14:46:25 [ERROR] Cannot download package "org.itxtech:mcl-addon" 14:46:25 [ERROR] The local file "org.itxtech:mcl-addon" is still corrupted, please check the network. 14:46:25 [INFO] Verifying "net.mamoe:mirai-api-http" v1.10.0 14:46:25 [ERROR] "net.mamoe:mirai-api-http" is corrupted. 14:46:26 [ERROR] Cannot download package "net.mamoe:mirai-api-http" 14:46:26 [ERROR] The local file "net.mamoe:mirai-api-http" is still corrupted, please check the network. 14:46:26 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.nio.file.NoSuchFileException: libs\mirai-console-2.10.0.jar (boot.js#98) at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160) at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226) at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692) at script(boot.js:98) at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013) at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578) at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107) at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43) at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155) at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105) at org.mozilla.javascript.Context.call(Context.java:554) at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522) at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105) at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126) at com.sun.proxy.$Proxy4.run(Unknown Source) at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106) at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176) at org.itxtech.mcl.Loader.tryCatching(Loader.java:145) at org.itxtech.mcl.Loader.start(Loader.java:176) at org.itxtech.mcl.Loader.main(Loader.java:68) Caused by: java.nio.file.NoSuchFileException: libs\mirai-console-2.10.0.jar at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source) at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source) at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source) at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source) at java.base/java.nio.file.Files.readAttributes(Unknown Source) at java.base/java.util.zip.ZipFile$Source.get(Unknown Source) at java.base/java.util.zip.ZipFile$CleanableResource.(Unknown Source) at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source) at java.base/java.util.zip.ZipFile.(Unknown Source) at java.base/java.util.zip.ZipFile.(Unknown Source) at java.base/java.util.jar.JarFile.(Unknown Source) at java.base/java.util.jar.JarFile.(Unknown Source) at java.base/java.util.jar.JarFile.(Unknown Source) at org.itxtech.mcl.Utility.bootMirai(Utility.java:76) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.base/java.lang.reflect.Method.invoke(Unknown Source) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138) ... 20 more

加群，里面有解决方法

**Comment by yar2001** [comment]
> 
> 加群，里面有解决方法

我也遇到了类似错误，请问群号是多少？

**Comment by yar2001** [comment]
另外，这个问题应该来自[mirai-console-loader](https://github.com/iTXTech/mirai-console-loader)，我用docker直接部署也出现了这个问题

https://github.com/iTXTech/mirai-console-loader/issues/96

**Comment by Tomoya114** [comment]
试了好多次一直下载失败，有解决的办法吗？😭😭😭
```java
 11:39:04 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
 11:39:04 [ERROR] "org.bouncycastle:bcprov-jdk15on" is corrupted.
 11:39:04 [ERROR] Cannot download package "org.bouncycastle:bcprov-jdk15on"
 11:39:04 [ERROR] The local file "org.bouncycastle:bcprov-jdk15on" is still corrupted, please check the network.

 11:39:04 [INFO] Verifying "net.mamoe:mirai-console" v2.10.0
 11:39:04 [ERROR] "net.mamoe:mirai-console" is corrupted.
 11:39:04 [ERROR] Cannot download package "net.mamoe:mirai-console"
 11:39:04 [ERROR] The local file "net.mamoe:mirai-console" is still corrupted, please check the network.

**Comment by PeratX** [comment]
可能是镜像抽风吧，现在测试过好像可以了

**Comment by gimfia** [comment]
> 

我把源

> 试了好多次一直下载失败，有解决的办法吗？😭😭😭
> 
> ```java
>  11:39:04 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
>  11:39:04 [ERROR] "org.bouncycastle:bcprov-jdk15on" is corrupted.
>  11:39:04 [ERROR] Cannot download package "org.bouncycastle:bcprov-jdk15on"
>  11:39:04 [ERROR] The local file "org.bouncycastle:bcprov-jdk15on" is still corrupted, please check the network.
> 
>  11:39:04 [INFO] Verifying "net.mamoe:mirai-console" v2.10.0
>  11:39:04 [ERROR] "net.mamoe:mirai-console" is corrupted.
>  11:39:04 [ERROR] Cannot download package "net.mamoe:mirai-console"
>  11:39:04 [ERROR] The local file "net.mamoe:mirai-console" is still corrupted, please check the network.
> ```

我把依赖源改成maven仓库，然后挂代理就可以了
