### ISSUE TITLE
error decoding response body: EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by xuke-hat** [iTXTech/mcl-installer#34]
用的是腾讯云的服务器，系统是Debian 11.1。根据README的方法安装的，不知道哪里出了问题。。

iTXTech MCL Installer 1.0.3 [OS: linux]
Licensed under GNU AGPLv3.
https://github.com/iTXTech/mcl-installer

iTXTech MCL and Java will be downloaded to "/home/xx"

Checking existing Java installation.
Error occurred while checking Java installation

Would you like to install Java? (Y/N, default: Y) 
Java version (8-17, default: 11): 
JRE or JDK (1: JRE, 2: JDK, default: JRE): 
Binary Architecture (default: x64): 
Fetching file list for jre version 11 on x64
Start Downloading: https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK/11/jre/x64/linux/OpenJDK11U-jre_x64_linux_hotspot_11.0.14.1_1.tar.gz
Downloading: 42434630/42434630
Extracting jdk-11.0.14.1+1-jre/legal/jdk.management/ADDITIONAL_LICENSE_INFOOFOOE_INFONFONSE_INFO
Testing Java Executable: /home/xx/java/bin/java
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)

Fetching iTXTech MCL Package Info from https://gitee.com/peratx/mirai-repo/raw/master/org/itxtech/mcl/package.json
[src/main.rs:335:10] Error: error decoding response body: EOF while parsing a value at line 1 column 0

**Comment by avawuw** [comment]
我也是这个问题，在Windows下尝试之后也一样，我感觉是gitee出错了

**Comment by avawuw** [comment]
有方法了，把如下的存在package.json然后再运行

{
    "type": "core",
    "defaultChannel": "stable",
    "announcement": "Mirai Console Loader 公告栏\n\n如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)\n`- 如 Unsupported image type for ExternalResource *\n`  considering use gif/png/bmp/jpg format.\n`- Tracker: https://github.com/mamoe/mirai/issues/new/choose\n\n常用资源整合\n`- https://mirai.mamoe.net/topic/653\n",
    "channels": {
        "stable": [
            "1.0.5",
            "1.1.0",
            "1.2.1",
            "1.2.2"
        ]
    },
    "repo": {
        "1.0.5": {
            "archive": "https://github.com/iTXTech/mirai-console-loader/releases/download/v1.0.5/mcl-1.0.5.zip"
        },
        "1.1.0": {
            "archive": "https://github.com/iTXTech/mirai-console-loader/releases/download/v1.1.0/mcl-1.1.0.zip"
        },
        "1.2.1": {
            "archive": "https://github.com/iTXTech/mirai-console-loader/releases/download/v1.2.1/mcl-1.2.1.zip"
        },
        "1.2.2": {
            "archive": "https://github.com/iTXTech/mirai-console-loader/releases/download/v1.2.2/mcl-1.2.2.zip"
        }
    }
}

**Comment by PeratX** [comment]
gitee禁止外部访问了，会进行修改

**Comment by avawuw** [comment]
已经完成更改和替换，可以前往https://github.com/avawuw/mcl-installer/releases
进行下载，务必下载最新编译的版本

**Comment by PeratX** [comment]
已修复

**Comment by xuke-hat** [comment]
现在mcl-installer没有问题了，但是安装完之后运行./mcl还是报错。安装时所有操作都是默认选项。
```
 13:47:39 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
 13:47:39 [INFO] https://github.com/iTXTech/mirai-console-loader
 13:47:39 [INFO] This program is licensed under GNU AGPL v3
 13:47:39 [INFO] Fetching Mirai Console Loader Announcement...
 13:47:40 [INFO] Mirai Console Loader Announcement:
 13:47:40 [ERROR] Failed to fetch announcement.
 13:47:40 [INFO] Verifying "net.mamoe:mirai-console" v
 13:47:40 [ERROR] "net.mamoe:mirai-console" is corrupted.
 13:47:40 [ERROR] Failed to verify package "net.mamoe:mirai-console"
 13:47:40 [ERROR] TypeError: Cannot read property "channels" from null
 13:47:40 [INFO] Verifying "net.mamoe:mirai-console-terminal" v
 13:47:40 [ERROR] "net.mamoe:mirai-console-terminal" is corrupted.
 13:47:40 [ERROR] Failed to verify package "net.mamoe:mirai-console-terminal"
 13:47:40 [ERROR] TypeError: Cannot read property "channels" from null
 13:47:40 [INFO] Verifying "net.mamoe:mirai-core-all" v
 13:47:40 [ERROR] "net.mamoe:mirai-core-all" is corrupted.
 13:47:40 [ERROR] Failed to verify package "net.mamoe:mirai-core-all"
 13:47:40 [ERROR] TypeError: Cannot read property "channels" from null
 13:47:40 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.nio.file.NoSuchFileException: libs/mirai-console-.jar (boot.js#98)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at script(boot.js:98)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.nio.file.NoSuchFileException: libs/mirai-console-.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
        at java.base/java.nio.file.Files.readAttributes(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        ... 20 more
```

**Comment by PeratX** [comment]
因为mcl还在发布新版本，等两分钟应该就能收到1.2.3更新，需要删除config.json
将 mirai-repo 更改为 https://repo.itxtech.org
