### ISSUE TITLE
无法登录，提示须最新版的QQ，但qq已经为最新板，重新安装也没用

### ISSUE THREAD

**Issue by zhumeng2333** [iTXTech/mcl-installer#61]
Login failed: Error(bot=Bot(3434782863), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点 击进入下载页面, errorInfo=)
2023-02-25 10:16:30 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3434782863), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3434782863), code=235, title=温馨提示, message=当前QQ版本 过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by PeratX** [comment]
请向mirai汇报
