### ISSUE TITLE
安装mcl-installer时的报错

### ISSUE THREAD

**Issue by Shigaharuki3012** [iTXTech/mcl-installer#68]
执行`./mcl-installer-1.0.7-macos-aarch64`的时候最后总是报错.
具体如下：
```
Fetching iTXTech MCL Package Info from https://mirai.mamoe.net/assets/mcl/org/itxtech/mcl/package.json
[src/main.rs:335:10] Error: error sending request for url (https://mirai.mamoe.net/assets/mcl/org/itxtech/mcl/package.json)
: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```
查了很多dns的解决方式好像都不行

**Comment by superen7527** [comment]
由于论坛已经关闭，该域名dns没解析到ip。程序没有支持错误处理，遇到错误就中断了，建议手动安装。

**Comment by Shigaharuki3012** [comment]
你好，非常感谢回复！
您是指手动安装mcl和java环境吗？我尝试着去java网站下载下来安装java环境，然后运行`./mcl`,结果仍然不是教程中的正确输出。
我的设备是Mac M1。mcl版本是1.0.7的macos-aarch64

**Comment by superen7527** [comment]
mkdir mcl
cd mcl
wget https://github.com/iTXTech/mirai-console-loader/releases/download/v2.1.2/mcl-2.1.2.zip
unzip mcl-2.1.2.zip
chmod +x mcl
./mcl

**Comment by Shigaharuki3012** [comment]
感谢您提供的方法，但是当我运行最后一步时，显示：
```
@CyberpsycodeMacBook-Air mcl % ./mcl
 16:31:01 [ERROR] Failed to verify package "org.bouncycastle:bcprov-jdk15on"
  16:31:01 [ERROR] java.net.ConnectException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:951)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at org.itxtech.mcl.component.Repository.httpGet(Repository.java:211)
	at org.itxtech.mcl.component.Repository.httpGet(Repository.java:206)
	at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:84)
	at org.itxtech.mcl.module.builtin.RepoCache$RepoWithCache.fetchPackage(RepoCache.java:88)

```
我之前的版本下载错了，于是换成了JDK17，但是无论是17还是21均是以上报错
